var GameTemplate =
{
  tokens:10,
  deck:100,
  hand:5,
  goal_shift_turns:3,
  players:
    [
      {
        title:"Player 1",
        token_img:"red_circle",
        color:"#FF0000",
      },
      {
        title:"Player 2",
        token_img:"blue_circle",
        color:"#0000FF",
      },
    ],
  nodes:
    [
      {
        title:"A",
        img:"circle",
        x:0.2,
        y:0.2,
        w:0.1,
        h:0.1,
      },
      {
        title:"B",
        img:"circle",
        x:0.4,
        y:0.1,
        w:0.1,
        h:0.1,
      },
      {
        title:"C",
        img:"circle",
        x:0.6,
        y:0.8,
        w:0.1,
        h:0.1,
      },
      {
        title:"D",
        img:"circle",
        x:0.7,
        y:0.4,
        w:0.1,
        h:0.1,
      },
    ],
  events:
    [
      {
        title:"EvA",
        description:"EvA Is a THING",
        from:"A",
        to:"B",
        time:0,
        amt:1,
        common:1,
      },
      {
        title:"EvB",
        description:"EvB Is a THING",
        from:"B",
        to:"C",
        time:0,
        amt:1,
        common:1,
      },
      {
        title:"EvC",
        description:"EvC Is a THING",
        from:"C",
        to:"D",
        time:0,
        amt:1,
        common:1,
      },
      {
        title:"EvD",
        description:"EvD Is a THING",
        from:"D",
        to:"B",
        time:0,
        amt:1,
        common:1,
      },
      {
        title:"EvE",
        description:"EvE Is a THING",
        from:"A",
        to:"C",
        time:0,
        amt:1,
        common:1,
      },
    ],
};

var OldCarbonCycleGameTemplate =
{
  tokens:10,
  deck:100,
  hand:5,
  goal_shift_turns:3,
  players:
    [
      {
        title:"Player 1",
        token_img:"red_circle",
        color:"#FF0000",
      },
      {
        title:"Player 2",
        token_img:"blue_circle",
        color:"#0000FF",
      },
    ],
  nodes:
    [
      {
        title:"Earth",
        img:"circle",
        x:0.5,
        y:0.4,
        w:0.1,
        h:0.1,
      },
      {
        title:"Atmosphere",
        img:"circle",
        x:0.3,
        y:0.4,
        w:0.1,
        h:0.1,
      },
      {
        title:"Plants",
        img:"circle",
        x:0.4,
        y:0.7,
        w:0.1,
        h:0.1,
      },
      {
        title:"Animals",
        img:"circle",
        x:0.7,
        y:0.7,
        w:0.1,
        h:0.1,
      },
      {
        title:"Fuel",
        img:"circle",
        x:0.7,
        y:0.3,
        w:0.1,
        h:0.1,
      },
    ],
  events:
    [
      {
        title:"Photosynth",
        description:"Makin' plants' energy!",
        from:"Atmosphere",
        to:"Plants",
        time:0,
        amt:1,
        common:1,
      },
      {
        title:"Eat",
        description:"Herbivores gotta eat...",
        from:"Plants",
        to:"Animals",
        time:0,
        amt:1,
        common:1,
      },
      {
        title:"Respiration",
        description:"BREEEEEAAAATHE",
        from:"Animals",
        to:"Atmosphere",
        time:0,
        amt:1,
        common:1,
      },
      {
        title:"Animal Death",
        description:"Sad to see them go.",
        from:"Animals",
        to:"Earth",
        time:0,
        amt:1,
        common:1,
      },
      {
        title:"Plant Death",
        description:"Not as sad to see them go.",
        from:"Plants",
        to:"Earth",
        time:0,
        amt:1,
        common:1,
      },
      {
        title:"Combustion",
        description:"BOOM",
        from:"Fuel",
        to:"Atmosphere",
        time:0,
        amt:2,
        common:1,
      },
      {
        title:"Million-Year Decay",
        description:"Turning Coal to Petroleum",
        from:"Earth",
        to:"Fuel",
        time:1,
        amt:1,
        common:1,
      },
    ],
};

var WaterCycleGameTemplate =
{
  tokens:10,
  deck:100,
  hand:5,
  goal_shift_turns:3,
  players:
    [
      {
        title:"Player 1",
        token_img:"red_circle",
        color:"#FF0000",
      },
      {
        title:"Player 2",
        token_img:"blue_circle",
        color:"#0000FF",
      },
    ],
  nodes:
    [
      {
        title:"Surface",
        img:"circle",
        x:0.5,
        y:0.4,
        w:0.1,
        h:0.1,
      },
      {
        title:"Earth",
        img:"circle",
        x:0.4,
        y:0.3,
        w:0.1,
        h:0.1,
      },
      {
        title:"River",
        img:"circle",
        x:0.3,
        y:0.5,
        w:0.1,
        h:0.1,
      },
      {
        title:"Ocean",
        img:"circle",
        x:0.7,
        y:0.4,
        w:0.1,
        h:0.1,
      },
      {
        title:"Atmosphere",
        img:"circle",
        x:0.7,
        y:0.6,
        w:0.1,
        h:0.1,
      },
      {
        title:"Clouds",
        img:"circle",
        x:0.5,
        y:0.7,
        w:0.1,
        h:0.1,
      },
    ],
  events:
    [
      {
        title:"Evaporation",
        description:"The air is thirsty",
        from:"Surface",
        to:"Atmosphere",
        time:0,
        amt:1,
        common:1,
      },
      {
        title:"Evaporation",
        description:"The air is thirsty",
        from:"Ocean",
        to:"Atmosphere",
        time:0,
        amt:1,
        common:1,
      },
      {
        title:"Evaporation",
        description:"The air is thirsty",
        from:"River",
        to:"Atmosphere",
        time:0,
        amt:1,
        common:1,
      },
      {
        title:"Runoff",
        description:"The water's gotta go somewhere...",
        from:"Surface",
        to:"River",
        time:0,
        amt:1,
        common:1,
      },
      {
        title:"Runoff",
        description:"The water's gotta go somewhere...",
        from:"Surface",
        to:"Ocean",
        time:0,
        amt:1,
        common:1,
      },
      {
        title:"Condensation",
        description:"Makes the air visible",
        from:"Atmosphere",
        to:"Clouds",
        time:0,
        amt:1,
        common:1,
      },
      {
        title:"Precipitation",
        description:"Rain Sleet Snow or Hail",
        from:"Clouds",
        to:"Ocean",
        time:0,
        amt:1,
        common:1,
      },
      {
        title:"Precipitation",
        description:"Rain Sleet Snow or Hail",
        from:"Clouds",
        to:"River",
        time:0,
        amt:1,
        common:1,
      },
      {
        title:"Precipitation",
        description:"Rain Sleet Snow or Hail",
        from:"Clouds",
        to:"Surface",
        time:0,
        amt:1,
        common:1,
      },
      {
        title:"Soil Absorption",
        description:"A sinking puddle",
        from:"Surface",
        to:"Earth",
        time:0,
        amt:1,
        common:1,
      },
      {
        title:"Ground Water Route to River",
        description:"I have nothing interesting to add",
        from:"Earth",
        to:"River",
        time:0,
        amt:1,
        common:1,
      },
      {
        title:"Ground Water Route to Ocean",
        description:"I have nothing interesting to add",
        from:"Earth",
        to:"Ocean",
        time:0,
        amt:1,
        common:1,
      },
    ],
};

var CarbonCycleGameTemplate =
{
  tokens:10,
  deck:100,
  hand:5,
  goal_shift_turns:3,
  players:
    [
      {
        title:"Player 1",
        token_img:"red_circle",
        color:"#FF0000",
      },
      {
        title:"Player 2",
        token_img:"blue_circle",
        color:"#0000FF",
      },
    ],
  nodes:
    [
      {
        title:"Atmosphere",
        img:"circle",
        x:0.5,
        y:0.75,
        w:0.1,
        h:0.1,
      },
      {
        title:"Animals",
        img:"circle",
        x:0.3,
        y:0.7,
        w:0.1,
        h:0.1,
      },
      {
        title:"Plants",
        img:"circle",
        x:0.45,
        y:0.5,
        w:0.1,
        h:0.1,
      },
      {
        title:"Earth (Surface)",
        img:"circle",
        x:0.3,
        y:0.4,
        w:0.1,
        h:0.1,
      },
      {
        title:"Earth (Deep)",
        img:"circle",
        x:0.45,
        y:0.3,
        w:0.1,
        h:0.1,
      },
      {
        title:"Fuel",
        img:"circle",
        x:0.7,
        y:0.65,
        w:0.1,
        h:0.1,
      },
      {
        title:"Factory",
        img:"circle",
        x:0.575,
        y:0.475,
        w:0.1,
        h:0.1,
      },
      {
        title:"Ocean (Surface)",
        img:"circle",
        x:0.7,
        y:0.4,
        w:0.1,
        h:0.1,
      },
      {
        title:"Ocean (Deep)",
        img:"circle",
        x:0.6,
        y:0.3,
        w:0.1,
        h:0.1,
      },
    ],
  events:
    [
      {
        title:"Animal Respiration",
        description:"BREATHE",
        from:"Animals",
        to:"Atmosphere",
        time:0,
        amt:1,
        common:1,
      },
      {
        title:"Plant Respiration",
        description:"Plants breathe too!",
        from:"Plants",
        to:"Atmosphere",
        time:0,
        amt:1,
        common:1,
      },
      {
        title:"Photosynthesis",
        description:"Turnin' sunshine to energy",
        from:"Atmosphere",
        to:"Plants",
        time:0,
        amt:1,
        common:1,
      },
      {
        title:"Herbivore",
        description:"Eat your veggies",
        from:"Plants",
        to:"Animals",
        time:0,
        amt:1,
        common:1,
      },
      {
        title:"Animal Death",
        description:"Poor things",
        from:"Animals",
        to:"Earth (Surface)",
        time:0,
        amt:1,
        common:1,
      },
      {
        title:"Plant Death",
        description:"Live and die",
        from:"Plants",
        to:"Earth (Surface)",
        time:0,
        amt:1,
        common:1,
      },
      {
        title:"Fire",
        description:"Mass plant eradication",
        from:"Plants",
        to:"Atmosphere",
        time:0,
        amt:3,
        common:1,
      },
      {
        title:"Soil Respiration",
        description:"Happens everywhere",
        from:"Earth (Surface)",
        to:"Atmosphere",
        time:0,
        amt:1,
        common:1,
      },
      {
        title:"Million-Year Decay",
        description:"From Coal to Petroleum",
        from:"Earth (Surface)",
        to:"Earth (Deep)",
        time:1,
        amt:1,
        common:1,
      },
      {
        title:"Harvest Oil",
        description:"That's one way to bring it back up",
        from:"Earth (Deep)",
        to:"Factory",
        time:0,
        amt:1,
        common:1,
      },
      {
        title:"Proccess Fossil Fuels",
        description:"Human intervention",
        from:"Factory",
        to:"Fuel",
        time:0,
        amt:1,
        common:1,
      },
      {
        title:"Combustion",
        description:"BOOM",
        from:"Fuel",
        to:"Atmosphere",
        time:0,
        amt:2,
        common:1,
      },
      {
        title:"Erosion",
        description:"One Big Resevoir to another",
        from:"Earth (Surface)",
        to:"Ocean (Surface)",
        time:0,
        amt:1,
        common:1,
      },
      {
        title:"Sinking Sediment",
        description:"Pretty straightforward process",
        from:"Ocean (Surface)",
        to:"Ocean (Deep)",
        time:0,
        amt:1,
        common:1,
      },
      {
        title:"Ocean Deposit",
        description:"Slowly reintegrate to land",
        from:"Ocean (Deep)",
        to:"Earth (Deep)",
        time:0,
        amt:1,
        common:1,
      },
      {
        title:"Ocean Diffusion",
        description:"Happens Everywhere- both ways!",
        from:"Ocean (Surface)",
        to:"Atmosphere",
        time:0,
        amt:1,
        common:1,
      },
      {
        title:"Ocean Diffusion",
        description:"Happens Everywhere- both ways!",
        from:"Atmosphere",
        to:"Ocean (Surface)",
        time:0,
        amt:1,
        common:1,
      },
    ],
};

var NitrogenCycleGameTemplate =
{
  tokens:10,
  deck:100,
  hand:5,
  goal_shift_turns:3,
  players:
    [
      {
        title:"Player 1",
        token_img:"red_circle",
        color:"#FF0000",
      },
      {
        title:"Player 2",
        token_img:"blue_circle",
        color:"#0000FF",
      },
    ],
  nodes:
    [
      {
        title:"Atmosphere",
        img:"circle",
        x:0.5,
        y:0.6,
        w:0.1,
        h:0.1,
      },
      {
        title:"Soil",
        img:"circle",
        x:0.5,
        y:0.3,
        w:0.1,
        h:0.1,
      },
      {
        title:"Plants",
        img:"circle",
        x:0.3,
        y:0.4,
        w:0.1,
        h:0.1,
      },
      {
        title:"Animals",
        img:"circle",
        x:0.7,
        y:0.4,
        w:0.1,
        h:0.1,
      },
    ],
  events:
    [
      {
        title:"Lightning",
        description:"Thunder Boomers",
        from:"Atmosphere",
        to:"Soil",
        time:0,
        amt:1,
        common:1,
      },
      {
        title:"Bacteria Digestion",
        description:"Toot",
        from:"Soil",
        to:"Atmosphere",
        time:0,
        amt:1,
        common:1,
      },
      {
        title:"Plant Assimilation",
        description:"Through the roots!",
        from:"Soil",
        to:"Plants",
        time:0,
        amt:1,
        common:1,
      },
      {
        title:"Plant Death",
        description:"Sorry, plants. :(",
        from:"Plants",
        to:"Soil",
        time:0,
        amt:1,
        common:1,
      },
      {
        title:"Animal Death",
        description:"Sad day.",
        from:"Animals",
        to:"Soil",
        time:0,
        amt:1,
        common:1,
      },
      {
        title:"Herbivorism",
        description:"High in fiber.",
        from:"Plants",
        to:"Animals",
        time:0,
        amt:1,
        common:1,
      },
      {
        title:"Nitrigen-Fixing Plant Bacteria",
        description:"Actually doesn't pass through the plant",
        from:"Atmosphere",
        to:"Soil",
        time:0,
        amt:1,
        common:1,
      },
    ],
};
