var GameTemplate =
{
  tokens:10,
  deck:100,
  hand:5,
  goal_shift_turns:3,
  players:
    [
      {
        title:"RED TEAM",
        token_img:"red_circle",
        color:"#FF0000",
      },
      {
        title:"BLUE TEAM",
        token_img:"blue_circle",
        color:"#0000FF",
      },
    ],
  nodes:
    [
      {
        title:"A",
        img:"circle",
        x:0.2,
        y:0.2,
        w:0.2,
        h:0.2,
      },
      {
        title:"B",
        img:"circle",
        x:0.4,
        y:0.2,
        w:0.2,
        h:0.2,
      },
      {
        title:"C",
        img:"circle",
        x:0.6,
        y:0.8,
        w:0.2,
        h:0.2,
      },
      {
        title:"D",
        img:"circle",
        x:0.7,
        y:0.4,
        w:0.2,
        h:0.2,
      },
    ],
  events:
    [
      {
        title:"EvA",
        flavor:"EvA Is a THING",
        description:"",
        from:"A",
        to:"B",
        time:0,
        amt:1,
        common:1,
      },
      {
        title:"EvB",
        flavor:"EvB Is a THING",
        description:"",
        from:"B",
        to:"C",
        time:0,
        amt:1,
        common:1,
      },
      {
        title:"EvC",
        flavor:"EvC Is a THING",
        description:"",
        from:"C",
        to:"D",
        time:0,
        amt:1,
        common:1,
      },
      {
        title:"EvD",
        flavor:"EvD Is a THING",
        description:"",
        from:"D",
        to:"B",
        time:0,
        amt:1,
        common:1,
      },
      {
        title:"EvE",
        flavor:"EvE Is a THING",
        description:"",
        from:"A",
        to:"C",
        time:0,
        amt:1,
        common:1,
      },
    ],
};

var rx = .16;
var ry = .12;
var w = .19;
var h = .145;
var x = 0.5;
var y = 0.57;

var CarbonCycleGameTemplate =
{
  tokens:14,
  deck:100,
  hand:5,
  goal_shift_turns:3,
  noun:"carbon",
  bg_img:"carbon_bg",
  fg_img:"carbon_fg",
  players:
    [
      {
        title:"RED TEAM",
        token_img:"red_circle",
        color:"#FF0000",
      },
      {
        title:"BLUE TEAM",
        token_img:"blue_circle",
        color:"#0000FF",
      },
    ],
  nodes:
    [
      {
        title:"Plants",
        img:"plants",
        icon_img:"plants",
        x:x,
        y:y,
        w:w,
        h:h,
      },
      {
        title:"Atmosphere",
        img:"atmosphere",
        icon_img:"atmosphere",
        x:x+Math.cos(Math.PI/2+((0/6)*Math.PI*2))*rx,
        y:y+Math.sin(Math.PI/2+((0/6)*Math.PI*2))*ry,
        w:w,
        h:h,
      },
      {
        title:"Animals",
        img:"animal",
        icon_img:"animal",
        x:x+Math.cos(Math.PI/2+((1/6)*Math.PI*2))*rx,
        y:y+Math.sin(Math.PI/2+((1/6)*Math.PI*2))*ry,
        w:w,
        h:h,
      },
      {
        title:"Earth (Surface)",
        img:"earth_surface",
        icon_img:"earth_surface",
        x:x+Math.cos(Math.PI/2+((2/6)*Math.PI*2))*rx,
        y:y+Math.sin(Math.PI/2+((2/6)*Math.PI*2))*ry,
        w:w,
        h:h,
      },
      {
        title:"Earth (Deep)",
        img:"earth_deep",
        icon_img:"earth_deep",
        x:x+Math.cos(Math.PI/2+((3/6)*Math.PI*2))*rx,
        y:y+Math.sin(Math.PI/2+((3/6)*Math.PI*2))*ry,
        w:w,
        h:h,
      },
      {
        title:"Ocean",
        img:"ocean",
        icon_img:"ocean",
        x:x+Math.cos(Math.PI/2+((4/6)*Math.PI*2))*rx,
        y:y+Math.sin(Math.PI/2+((4/6)*Math.PI*2))*ry,
        w:w,
        h:h,
      },
      {
        title:"Fuel",
        img:"fuel",
        icon_img:"fuel",
        x:x+Math.cos(Math.PI/2+((5/6)*Math.PI*2))*rx,
        y:y+Math.sin(Math.PI/2+((5/6)*Math.PI*2))*ry,
        w:w,
        h:h,
      },
    ],
  events:
    [
      {
        title:"Animal Respiration",
        flavor:"Breathe in, breathe out",
        description:"When animals breathe, they take O₂ from and release CO₂ into the air!",
        from:"Animals",
        to:"Atmosphere",
        time:0,
        amt:1,
        common:1,
      },
      {
        title:"Plant Respiration",
        flavor:"Plants breathe too!",
        description:"Like animals, plants take O₂ from and release CO₂ into the air! (Though they also take CO₂ back in- but that's a different process!)",
        from:"Plants",
        to:"Atmosphere",
        time:0,
        amt:1,
        common:1,
      },
      {
        title:"Photosynthesis",
        flavor:"Turn sunshine to energy",
        description:"Plants take in CO₂ along with Sunlight to create energy and grow!",
        from:"Atmosphere",
        to:"Plants",
        time:0,
        amt:1,
        common:1.5,
      },
      {
        title:"Herbivorism",
        flavor:"Eat your veggies",
        description:"Since plants (and animals) are Carbon-Based, simply eating a plant is one of the simplest ways carbon is moved!",
        from:"Plants",
        to:"Animals",
        time:0,
        amt:1,
        common:1,
      },
      {
        title:"Animal Death",
        flavor:"Poor things",
        description:"Animals die and quickly decompose, leaving all of their carbon (and other matter!) behind on the Earth's surface",
        from:"Animals",
        to:"Earth (Surface)",
        time:0,
        amt:1,
        common:1,
      },
      {
        title:"Plant Death",
        flavor:"Wither away",
        description:"Plants die and quickly decompose, leaving all of their carbon (and other matter!) behind on the Earth's surface",
        from:"Plants",
        to:"Earth (Surface)",
        time:0,
        amt:1,
        common:1,
      },
      {
        title:"Soil Respiration",
        flavor:"Constant flow",
        description:"The living organisms within the soil respire their CO₂ into the soil. This results in a constant leak of CO₂ from the soil to the atmosphere!",
        from:"Earth (Surface)",
        to:"Atmosphere",
        time:0,
        amt:1,
        common:1,
      },
      {
        title:"Million-Year Decay",
        flavor:"From Coal to Petroleum",
        description:"Plant and Animal matter sink deep into the earth where they are left to decay and decompose for millions of years.",
        from:"Earth (Surface)",
        to:"Earth (Deep)",
        time:0,
        amt:1,
        common:0.5,
      },
      {
        title:"Harvest/Process Petroleum",
        flavor:"Drill, baby, drill!",
        description:"Petroleum must be harvested from deep within the earth. It then must be refined before it can be used for fuel.",
        from:"Earth (Deep)",
        to:"Fuel",
        time:0,
        amt:1,
        common:0.75,
      },
      {
        title:"Combustion",
        flavor:"BOOM",
        description:"To convert fuel into energy, we light it on fire! This releases large amounts of CO₂ into the atmosphere.",
        from:"Fuel",
        to:"Atmosphere",
        time:0,
        amt:1,
        common:1,
      },
      {
        title:"Erosion",
        flavor:"One Big Resevoir to another",
        description:"Deposits of carbon constantly get scraped off of the land by rushing currents over millions of years.",
        from:"Earth (Surface)",
        to:"Ocean",
        time:0,
        amt:1,
        common:1,
      },
      {
        title:"Ocean Deposit",
        flavor:"Slowly reintegrate to land",
        description:"Deposits of carbon in the ocean (and other bodies of water) slosh up on and leak into land.",
        from:"Ocean",
        to:"Earth (Deep)",
        time:0,
        amt:1,
        common:1,
      },
      {
        title:"Ocean Diffusion",
        flavor:"Exchanges in both directions!",
        description:"When there is more carbon in the Ocean than in the Atmosphere, it will leak into the atmosphere to even it out!",
        from:"Ocean",
        to:"Atmosphere",
        time:0,
        amt:1,
        common:0.5,
      },
      {
        title:"Ocean Diffusion",
        flavor:"Exchanges in both directions!",
        description:"When there is more carbon in the Atmosphere than in the Ocean, it will leak into the ocean to even it out!",
        from:"Atmosphere",
        to:"Ocean",
        time:0,
        amt:1,
        common:0.5,
      },
    ],
};


var WaterCycleGameTemplate =
{
  tokens:10,
  deck:100,
  hand:5,
  goal_shift_turns:3,
  noun:"water",
  bg_img:"water_bg",
  fg_img:"water_fg",
  players:
    [
      {
        title:"RED TEAM",
        token_img:"red_circle",
        color:"#FF0000",
      },
      {
        title:"BLUE TEAM",
        token_img:"blue_circle",
        color:"#0000FF",
      },
    ],
  nodes:
    [
      {
        title:"Surface",
        img:"earth_surface",
        icon_img:"earth_surface",
        x:x,
        y:y,
        w:w,
        h:h,
      },
      {
        title:"Clouds",
        img:"atmosphere",
        icon_img:"atmosphere",
        x:x+Math.cos(Math.PI/2+((0/6)*Math.PI*2))*rx,
        y:y+Math.sin(Math.PI/2+((0/6)*Math.PI*2))*ry,
        w:w,
        h:h,
      },
      {
        title:"River",
        img:"ocean",
        icon_img:"ocean",
        x:x+Math.cos(Math.PI/2+((2/6)*Math.PI*2))*rx,
        y:y+Math.sin(Math.PI/2+((2/6)*Math.PI*2))*ry,
        w:w,
        h:h,
      },
      {
        title:"Earth",
        img:"earth_deep",
        icon_img:"earth_deep",
        x:x+Math.cos(Math.PI/2+((3/6)*Math.PI*2))*rx,
        y:y+Math.sin(Math.PI/2+((3/6)*Math.PI*2))*ry,
        w:w,
        h:h,
      },
      {
        title:"Ocean",
        img:"ocean",
        icon_img:"ocean",
        x:x+Math.cos(Math.PI/2+((4/6)*Math.PI*2))*rx,
        y:y+Math.sin(Math.PI/2+((4/6)*Math.PI*2))*ry,
        w:w,
        h:h,
      },
      {
        title:"Atmosphere",
        img:"atmosphere",
        icon_img:"atmosphere",
        x:x+Math.cos(Math.PI/2+((5/6)*Math.PI*2))*rx,
        y:y+Math.sin(Math.PI/2+((5/6)*Math.PI*2))*ry,
        w:w,
        h:h,
      },
    ],
  events:
    [
      {
        title:"Evaporation",
        flavor:"Disappearing into thin air",
        description:"Water on Earth's surface will quickly dissapate into the atmosphere, so long as it isn't very humid.",
        from:"Surface",
        to:"Atmosphere",
        time:0,
        amt:1,
        common:1,
      },
      {
        title:"Evaporation",
        flavor:"Disappearing into thin air",
        description:"The Ocean is constantly contributing to the humidity of the atmosphere surrounding it.",
        from:"Ocean",
        to:"Atmosphere",
        time:0,
        amt:1,
        common:1,
      },
      {
        title:"Evaporation",
        flavor:"The air is thirsty",
        description:"Rivers and Lakes constantly contribute to the humidity of the atmosphere surrounding them.",
        from:"River",
        to:"Atmosphere",
        time:0,
        amt:1,
        common:1,
      },
      {
        title:"Runoff",
        flavor:"The water's gotta go somewhere...",
        description:"Water from rain, agriculture, or anything else on the surface will eventually make its way lower- in this case, a nearby river.",
        from:"Surface",
        to:"River",
        time:0,
        amt:1,
        common:1,
      },
      {
        title:"Runoff",
        flavor:"The water's gotta go somewhere...",
        description:"Water from rain, agriculture, or anything else on the surface will eventually make its way lower- in this case, the nearby ocean.",
        from:"Surface",
        to:"Ocean",
        time:0,
        amt:1,
        common:1,
      },
      {
        title:"Condensation",
        flavor:"Makes the air visible",
        description:"When the air gets humid and cold enough (like high in the atmosphere), it will condense into a visible mist (seen as fog or clouds).",
        from:"Atmosphere",
        to:"Clouds",
        time:0,
        amt:1,
        common:1,
      },
      {
        title:"Precipitation",
        flavor:"Rain Sleet Snow or Hail",
        description:"Enough condensed water will become heavy enough to fall down to the earth- or in this case, the ocean.",
        from:"Clouds",
        to:"Ocean",
        time:0,
        amt:1,
        common:1,
      },
      {
        title:"Precipitation",
        flavor:"Rain Sleet Snow or Hail",
        description:"Enough condensed water will become heavy enough to fall down to the earth- or in this case, a river.",
        from:"Clouds",
        to:"River",
        time:0,
        amt:1,
        common:1,
      },
      {
        title:"Precipitation",
        flavor:"Rain Sleet Snow or Hail",
        description:"Enough condensed water will become heavy enough to fall down to the earth.",
        from:"Clouds",
        to:"Surface",
        time:0,
        amt:1,
        common:1,
      },
      {
        title:"Soil Absorption",
        flavor:"A sinking puddle",
        description:"Water left alone on soft earth will sink deep into the ground if it doesn't evaporate quickly enough.",
        from:"Surface",
        to:"Earth",
        time:0,
        amt:1,
        common:1,
      },
      {
        title:"Ground Water Expansion",
        flavor:"Big reservoirs in motion",
        description:"Even large stores of water deep within the earth can find their ways to other bodies of water- in this case, a river.",
        from:"Earth",
        to:"River",
        time:0,
        amt:1,
        common:1,
      },
      {
        title:"Ground Water Expansion",
        flavor:"Big reservoirs in motion",
        description:"Even large stores of water deep within the earth can find their ways to other bodies of water- in this case, the ocean.",
        from:"Earth",
        to:"Ocean",
        time:0,
        amt:1,
        common:1,
      },
    ],
};

var NitrogenCycleGameTemplate =
{
  tokens:10,
  deck:100,
  hand:5,
  goal_shift_turns:3,
  noun:"nitrogen",
  bg_img:"nitrogen_bg",
  fg_img:"nitrogen_fg",
  players:
    [
      {
        title:"RED TEAM",
        token_img:"red_circle",
        color:"#FF0000",
      },
      {
        title:"BLUE TEAM",
        token_img:"blue_circle",
        color:"#0000FF",
      },
    ],
  nodes:
    [
      {
        title:"Atmosphere",
        img:"atmosphere",
        icon_img:"atmosphere",
        x:x+Math.cos(Math.PI/2+((0/6)*Math.PI*2))*rx,
        y:y+Math.sin(Math.PI/2+((0/6)*Math.PI*2))*ry,
        w:w,
        h:h,
      },
      {
        title:"Plants",
        img:"plants",
        icon_img:"plants",
        x:x,
        y:y,
        w:w,
        h:h,
      },
      {
        title:"Soil",
        img:"earth_surface",
        icon_img:"earth_surface",
        x:x+Math.cos(Math.PI/2+((3/6)*Math.PI*2))*rx,
        y:y+Math.sin(Math.PI/2+((3/6)*Math.PI*2))*ry,
        w:w,
        h:h,
      },
      {
        title:"Animals",
        img:"animal",
        icon_img:"animal",
        x:x+Math.cos(Math.PI/2+((5/6)*Math.PI*2))*rx,
        y:y+Math.sin(Math.PI/2+((5/6)*Math.PI*2))*ry,
        w:w,
        h:h,
      },
    ],
  events:
    [
      {
        title:"Lightning",
        flavor:"Thunder Boomers",
        description:"The energy from a lightning strike converts Nitrogen and Oxygen in the air to Nitrates (which can be used by plants!). The rain then washes the nitrates into the soil.",
        from:"Atmosphere",
        to:"Soil",
        time:0,
        amt:1,
        common:1,
      },
      {
        title:"Bacteria Digestion",
        flavor:"Toot",
        description:"Different bacteria consume and release nitrogen in different forms: From Ammonia to Nitrate, and Nitrate to N₂ (also known as Nitrogen gas).",
        from:"Soil",
        to:"Atmosphere",
        time:0,
        amt:1,
        common:1,
      },
      {
        title:"Plant Assimilation",
        flavor:"Through the roots!",
        description:"Plants take up the Nitrogen in the soil through their roots, providing the nutrition they need to live.",
        from:"Soil",
        to:"Plants",
        time:0,
        amt:1,
        common:1,
      },
      {
        title:"Plant Death",
        flavor:"Wither away",
        description:"Any Nitrogen left in a plant when it dies simply returns to the soil as the plant decays.",
        from:"Plants",
        to:"Soil",
        time:0,
        amt:1,
        common:1,
      },
      {
        title:"Animal Death",
        flavor:"Poor things",
        description:"Plants get Nitrogen from the soil, Animals get Nitrogen from eating plants, and when animals die, their Nitrogen returns to the soil.",
        from:"Animals",
        to:"Soil",
        time:0,
        amt:1,
        common:1,
      },
      {
        title:"Herbivorism",
        flavor:"Eat your veggies",
        description:"Eating Nitrogen-rich plants is a simple way for an animal to get its Nitrogen!",
        from:"Plants",
        to:"Animals",
        time:0,
        amt:1,
        common:1,
      },
      {
        title:"Nitrigen-Fixing Plant Bacteria",
        flavor:"Bacteria doing work",
        description:"Some bacteria live symbiotically with plants, converting Nitrogen gas in the atmosphere into the soil in forms usable by plants.",
        from:"Atmosphere",
        to:"Soil",
        time:0,
        amt:1,
        common:1,
      },
    ],
};
